export const Fonts = {
  alkalami: 'Alkalami-Regular',
  allura: 'Allura-Regular',
  poppins: {
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    light: 'Poppins-Light',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
  },
  robotoCondensed: {
    black: 'Roboto_Condensed-Black',
    blackItalic: 'Roboto_Condensed-BlackItalic',
    bold: 'Roboto_Condensed-Bold',
    boldItalic: 'Roboto_Condensed-BoldItalic',
    extraBold: 'Roboto_Condensed-ExtraBold',
    extraBoldItalic: 'Roboto_Condensed-ExtraBoldItalic',
    extraLight: 'Roboto_Condensed-ExtraLight',
    extraLightItalic: 'Roboto_Condensed-ExtraLightItalic',
    italic: 'Roboto_Condensed-Italic',
    light: 'Roboto_Condensed-Light',
    lightItalic: 'Roboto_Condensed-LightItalic',
    medium: 'Roboto_Condensed-Medium',
    mediumItalic: 'Roboto_Condensed-MediumItalic',
    regular: 'Roboto_Condensed-Regular',
    semiBold: 'Roboto_Condensed-SemiBold',
    semiBoldItalic: 'Roboto_Condensed-SemiBoldItalic',
    thin: 'Roboto_Condensed-Thin',
    thinItalic: 'Roboto_Condensed-ThinItalic',
  },
  robotoSemiCondensed: {
    black: 'Roboto_SemiCondensed-Black',
    blackItalic: 'Roboto_SemiCondensed-BlackItalic',
    bold: 'Roboto_SemiCondensed-Bold',
    boldItalic: 'Roboto_SemiCondensed-BoldItalic',
    extraBold: 'Roboto_SemiCondensed-ExtraBold',
    extraBoldItalic: 'Roboto_SemiCondensed-ExtraBoldItalic',
    extraLight: 'Roboto_SemiCondensed-ExtraLight',
    extraLightItalic: 'Roboto_SemiCondensed-ExtraLightItalic',
    italic: 'Roboto_SemiCondensed-Italic',
    light: 'Roboto_SemiCondensed-Light',
    lightItalic: 'Roboto_SemiCondensed-LightItalic',
    medium: 'Roboto_SemiCondensed-Medium',
    mediumItalic: 'Roboto_SemiCondensed-MediumItalic',
    regular: 'Roboto_SemiCondensed-Regular',
    semiBold: 'Roboto_SemiCondensed-SemiBold',
    semiBoldItalic: 'Roboto_SemiCondensed-SemiBoldItalic',
    thin: 'Roboto_SemiCondensed-Thin',
    thinItalic: 'Roboto_SemiCondensed-ThinItalic',
  },
  roboto: {
    black: 'Roboto-Black',
    blackItalic: 'Roboto-BlackItalic',
    bold: 'Roboto-Bold',
    boldItalic: 'Roboto-BoldItalic',
    extraBold: 'Roboto-ExtraBold',
    extraBoldItalic: 'Roboto-ExtraBoldItalic',
    extraLight: 'Roboto-ExtraLight',
    extraLightItalic: 'Roboto-ExtraLightItalic',
    italic: 'Roboto-Italic',
    light: 'Roboto-Light',
    lightItalic: 'Roboto-LightItalic',
    medium: 'Roboto-Medium',
    mediumItalic: 'Roboto-MediumItalic',
    regular: 'Roboto-Regular',
    semiBold: 'Roboto-SemiBold',
    semiBoldItalic: 'Roboto-SemiBoldItalic',
    thin: 'Roboto-Thin',
    thinItalic: 'Roboto-ThinItalic',
    variableFontWidthWeight: 'Roboto-VariableFont_wdth,wght',
    italicVariableFontWidthWeight: 'Roboto-Italic-VariableFont_wdth,wght',
  },

  gelasio: {
  bold: 'Gelasio-Bold',
  boldItalic: 'Gelasio-BoldItalic',
  italic: 'Gelasio-Italic',
  medium: 'Gelasio-Medium',
  mediumItalic: 'Gelasio-MediumItalic',
  regular: 'Gelasio-Regular',
  semiBold: 'Gelasio-SemiBold',
  semiBoldItalic: 'Gelasio-SemiBoldItalic',
  variableItalic: 'Gelasio-Italic-VariableFont_wght',
  variable: 'Gelasio-VariableFont_wght',
},

 avenir: {
    light: 'Avenir LT Pro 35 Light',
    black: 'AvenirLTProBlack',
    blackOblique: 'AvenirLTProBlackOblique',
    book: 'AvenirLTProBook',
    bookOblique: 'AvenirLTProBookOblique',
    heavy: 'AvenirLTProHeavy',
    heavyOblique: 'AvenirLTProHeavyOblique',
    lightNormal: 'AvenirLTProLight',
    lightOblique: 'AvenirLTProLightOblique',
    medium: 'AvenirLTProMedium',
    mediumOblique: 'AvenirLTProMediumOblique',
    oblique: 'AvenirLTProOblique',
    roman: 'AvenirLTProRoman',
  },

  abyssinicaSIL: 'AbyssinicaSIL-Regular',

};